name: Feature Request
description: Suggest an idea for this project
title: 'feat: <title>'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! We appreciate your input to help improve the project.
  - type: checkboxes
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if a similar feature request already exists.
      options:
        - label: I have searched the existing issues and feature requests
          required: true

  - type: textarea
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you're proposing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem and Motivation
      description: Describe the problem or limitation that this feature would address. Why is this feature needed?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working. Be as specific as possible.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features? If so, please describe them.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, or examples about the feature request here.

        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
